build:
  image: node:6
  commands:

    - npm i --loglevel silent

    # - wget -c wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    # - dpkg -i google-chrome-*.deb
    # - apt-get install -f
    # - apt-get update
    # - apt-get install -y default-jre
    # - npm i -g protractor
    # - webdriver-manager update
    # - webdriver-manager start &
    # - npm run test-ui

    - npm rebuild leveldown
    - npm rebuild levelup
    - npm rebuild node-sass
    - npm rebuild phantomjs-prebuilt
    - npm run test-unitserver
    - VAULT_PASS="$$VAULT_PASS_DEVSHOP" ./vault/decrypt.sh
    - DB_PATH=/tmp/db npm run test-integration
    - npm run test-unitclient
    - npm run lint
deploy:
  rsync:
    user: $$PROD_USER
    host: $$PROD_HOST
    port: 22
    source: ./docker-compose.yml
    target: /tmp/$$COMMIT/
    delete: false
    commands:
      - docker-compose -f /tmp/$$COMMIT/docker-compose.yml pull
      - VAULT_PASS_DEVSHOP=$$VAULT_PASS_DEVSHOP docker-compose -f /tmp/$$COMMIT/docker-compose.yml -p devshop-vtex up -d
    when:
      branch: master

publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    storage_driver: vfs
    repo: omelhoro1/devshop-vtex
    when:
      branch: master
